#! /bin/bash
set -eu
MIN_BAT=15
MAX_BAT=99

while true ; do
UNPLUGGED=`cat /sys/bus/acpi/drivers/battery/*/power_supply/BAT0/status`
BAT_PERCENTAGE=`acpi|grep -Po "[0-9]+(?=%)"`

if [ $BAT_PERCENTAGE -le $MIN_BAT ]; then # Battery under low limit
 if [ "$UNPLUGGED" == "Discharging" ]; then # unplugged
 notify-send --icon=battery-low "Battery under $MIN_BAT%. Please plug in the adapter"
 fi
fi

if [ $BAT_PERCENTAGE -ge $MAX_BAT ]; then # Battery over high limit
 if [ "$UNPLUGGED" == "Charging" ]; then # plugged
 notify-send --icon=dialog-information "Battery above $MAX_BAT%. Please remove the adapter"
 fi
fi
 
sleep 10 #Repeat every 10 seconds
done

